name: CI/CD Demo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Optional: PHP lint
      - name: PHP Syntax Check
        run: |
          find . -name "*.php" -print0 | xargs -0 -n1 php -l

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t nandhanas/adminer-demo:${{ github.sha }} .

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: nandhanas
          password: dckr_pat_FmtikC0x7EMLiWzlXnJh88hiTEY

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push nandhanas/adminer-demo:${{ github.sha }}

      # Set up Google Cloud SDK (FIXED)
       - name: Set up Google Cloud SDK
         uses: google-github-actions/setup-gcloud@v2
         with:
           project_id: secret-backbone-426709-n9
           service_account_key: ${{ secrets.GCP_SA_KEY }}
           export_default_credentials: true

      # Deploy public Adminer image to Cloud Run
      - name: Deploy public Adminer image to Cloud Run
        run: |
          gcloud run deploy stoxx-app \
            --image adminer \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --project secret-backbone-426709-n9
